### ISSUE TITLE
Happy new repo (and year) and gitignore

### ISSUE THREAD

**Issue by gndaskalova** [izzyrich/dissertation#1]
Hi @izzyrich 

Happy New Year and happy new repo!

I saw that there are a few DS_Store files and then I checked out your `.gitignore` file and it does have the DS_Store files there, so I'm not quite sure why they're not getting picked up, but thought I could let you know so that you look into it.

**Comment by izzyrich** [comment]
Hi Gergana, 

I think I set up the repo in sort of the wrong order and then had trouble merging everything, but it is all fixed now! Thanks for warning me!

Izzy
