### ISSUE TITLE
Feedback on one page summary and supporting forms

### ISSUE THREAD

**Issue by izzyrich** [izzyrich/dissertation#3]
Hi Isla and Gergana, 

I have just completed a draft of the one-page summary and supporting forms. Your feedback at your earliest convenience would be greatly appreciated! Feel free to add any comments here and/or directly in the Word documents.

Thanks! 

Izzy

**Comment by IslaMS** [comment]
Hi @izzyrich ,

I have added some comments to a version of your one page summary.  I am a bit busy tomorrow during the day, so I wanted to get these comments to you now.  I will do the forms tomorrow evening my time.  Will that work for your schedule?

Isla

**Comment by gndaskalova** [comment]
Hi @izzyrich 

I have added my comments on top of Isla's and have pushed the file - I think your .Rproj file is not in the gitignore and that's why you were having problems before?

Good luck with the edits and I'm looking forward to seeing your project unravel!

<img width="412" alt="screen shot 2019-01-16 at 11 24 39 am" src="https://user-images.githubusercontent.com/22785802/51242976-9dc63900-1981-11e9-901c-40056b30edd1.png">

**Comment by IslaMS** [comment]
Hey @izzyrich ,

The forms are signed!

Isla

**Comment by izzyrich** [comment]
Hi @IslaMS and @gndaskalova,

Thank you for all your helpful and thought-provoking comments!

I definitely need to still work on my questions and how I am framing them. I'm going to have mind mapping session tonight to try to figure it out. 

Just as a heads up: I've added a weekly goals calendar type thing in my README so I can keep myself on track a bit more. 

Thanks again,
Izzy

**Comment by gndaskalova** [comment]
Hey @izzyrich 

Just one quick thing to consider as you plan ahead and organise your time - I personally find it easier to not split data analysis from the writing, and be doing both in parallel. That way having to write your dissertation is not this big intimidating task, and you don't need to be done with your data analysis to start writing (also, quite often you are never really done with analyses, so then if you wait for that point, you might run out of time to write).

So up to you to structure your time, just a suggestion (e.g. you can have small writing goals each week).

**Comment by izzyrich** [comment]
Thanks for that thought, Gergana! I'll keep that in mind as I go! For now, it should be fine, but I may switch to more concrete and combined goals as I enter the analysis stage.
