### ISSUE TITLE
General questions I could use help with

### ISSUE THREAD

**Issue by izzyrich** [izzyrich/dissertation#5]
Hi @IslaMS and @gndaskalova,

I hope you're both well. I have some general questions that I could use your help with.

1. Should I try to get rid of clouds more? I have done something simple that I saw in a tutorial:

`var composite = ee.Algorithms.Landsat.simpleComposite({
  collection: landsatCollection,
  asFloat: true
});`

I think it is pretty basic. I have seen other methods online, but it would be nice to know what you both recommend. I'm not sure how to tell if this is an issue for me, to be honest. 

2. Do you recommend, as another way of assessing accuracy, using a validation set? If so, I will use CORINE. 
      2a. Leading off of that, is there a way to check that my points from LUCAS have loaded correctly other than just visually? It seems a bit scary to just accept that they are all correct and indicate abandoned land/other land types.

3. Do I need to divide up Latvia into sections if I'm looking at pixels? I remember speaking about this before, but I don't see why it would be important other than being able to talk about certain areas that may be experiencing land-use change differently than others. If either/both of you see the benefit of dividing up Latvia, please point me to how I could go about doing this.

4. Should I make an 'other' classification type? Obviously, not all land will be either abandoned, extensive or intensive, and I think an 'other' category would help improve classification accuracy. Let me know if you think this is the best option or maybe there is something better you have in mind.

5. I need a bit more help on how to apply my classification over time (over different image sets and years). Gergana pointed me to one of her scripts and I've been looking a lot online but I'm having trouble understanding how to do this. As far as I understand, I need to iterate through 4 different Landsat collections to cover 1979-2018 (Landsat 3: 1979-1982, Landsat 4: 1983-1984, Landsat 5: 1985-1998, Landsat 7: 1999-2018). If you have any more resources about this, that would be greatly appreciated. 

Sorry for the extremely long issue! Thanks for any help you can provide.

Izzy

**Comment by gndaskalova** [comment]
Hi @izzyrich 

I heard you discussed the points you've mentioned before with Isla, but just wanted to mention that in general for code-related questions, it'd be easier for us to help you if you paste the links to your GEE code (or mention the file path to the R script in case it's an R problem).

Have a nice day,
Gergana

**Comment by izzyrich** [comment]
> Hi @izzyrich
> 
> I heard you discussed the points you've mentioned before with Isla, but just wanted to mention that in general for code-related questions, it'd be easier for us to help you if you paste the links to your GEE code (or mention the file path to the R script in case it's an R problem).
> 
> Have a nice day,
> Gergana

Yes, I have! My notes on the questions can be found in the [meeting_notes](https://github.com/izzyrich/dissertation/blob/master/notes/meeting_notes.docx) document. I will keep that in mind for the future and remember to link everything!
